name: Unit Test

on: push

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.6', '3.7']
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    name: Test py ${{ matrix.python-version }} on ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: pip install numpy cython pytest
      - run: pip install -e .
      - run: python -m pytest -x ./tests
